version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_jobberu
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_jobberu
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    # Sobrescreve o comando do Dockerfile para usar o modo DEV (nodemon)
    command: npm run dev

volumes:
  pgdata:
