version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_jobberu
    environment:
      POSTGRES_USER: jobberu
      POSTGRES_PASSWORD: jobberu123
      POSTGRES_DB: mydatabasejoberu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_jobberu
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://jobberu:jobberu123@db:5432/mydatabasejoberu"
    depends_on:
      - db

volumes:
  pgdata:
